### ISSUE TITLE
Does command option conflict with pytest?

### ISSUE THREAD

**Issue by mingkim** [jcooky/jandy#52]
When I profile Flask module with Jandy profiler, below error is occurred.
Flask is using pytest module for their testing and I guess "-m" command conflicts when Jandy adds this to script part of .jandy.yml file.

https://pytest.org/latest/usage.html

```
(test_import)gimmyeongjuui-MacBook-Pro:tests nuko$ jandy
===================================================================== test session starts =====================================================================
platform darwin -- Python 3.4.3, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /Users/nuko/Git/flask, inifile: setup.cfg
plugins: cov-2.2.1, httpbin-0.2.0, mock-0.11.0
collected 292 items 

============================================================ 292 tests deselected by "-m 'jandy'" =============================================================
=============================================================== 292 deselected in 0.15 seconds ================================================================
Traceback (most recent call last):
  File "/Users/nuko/.virtualenvs/test_import/lib/python3.4/shutil.py", line 523, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'python-profiler-result.jandy' -> 'Mytest.jandy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nuko/.virtualenvs/test_import/bin/jandy", line 75, in <module>
    do_profile(yml['language'].lower(), sampleId, argv)
  File "/Users/nuko/.virtualenvs/test_import/bin/jandy", line 55, in do_profile
    shutil.move('python-profiler-result.jandy', id + '.jandy'),
  File "/Users/nuko/.virtualenvs/test_import/lib/python3.4/shutil.py", line 535, in move
    copy2(src, real_dst)
  File "/Users/nuko/.virtualenvs/test_import/lib/python3.4/shutil.py", line 245, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/nuko/.virtualenvs/test_import/lib/python3.4/shutil.py", line 108, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'python-profiler-result.jandy'
```

**Comment by mingkim** [comment]
Related pytest document

https://pytest.org/latest/example/markers.html#marking-test-functions-and-selecting-them-for-a-run

**Comment by mingkim** [comment]
make a new argparse custom option to support this issue

https://docs.python.org/3.4/howto/argparse.html
